// <auto-generated />
using System;
using LostAndFound.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostAndFound.Infrastructure.Migrations
{
    [DbContext(typeof(LostAndFoundDbContext))]
    partial class LostAndFoundDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LostAndFound.Domain.Entities.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__campus__3213E83FC0778A98");

                    b.HasIndex(new[] { "Code" }, "UQ__campus__357D4CF9EBCFDE3A")
                        .IsUnique();

                    b.ToTable("campus", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.EmailOtp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("otp_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<bool?>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("otp_code");

                    b.Property<string>("Purpose")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("purpose");

                    b.HasKey("OtpId")
                        .HasName("PK__EmailOTP__AEE354357865FADF");

                    b.HasIndex(new[] { "Email", "Purpose", "IsUsed", "ExpiresAt" }, "IX_EmailOTP_Email_Purpose_IsUsed");

                    b.ToTable("EmailOTP", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.ItemCategories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__item_cat__3213E83F9B10806D");

                    b.HasIndex(new[] { "Name" }, "UQ__item_cat__72E12F1B31B5FC09")
                        .IsUnique();

                    b.ToTable("item_categories", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.SecurityReceivedItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("campus_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FoundLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("found_location");

                    b.Property<DateTime>("FoundTime")
                        .HasColumnType("datetime")
                        .HasColumnName("found_time");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("item_category_id");

                    b.Property<int>("SecurityId")
                        .HasColumnType("int")
                        .HasColumnName("security_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__security__3213E83FAF1F12ED");

                    b.HasIndex("CampusId");

                    b.HasIndex("ItemCategoryId");

                    b.HasIndex("SecurityId");

                    b.ToTable("security_received_items", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.SecurityVerificationDecisions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("decision");

                    b.Property<int>("SecurityId")
                        .HasColumnType("int")
                        .HasColumnName("security_id");

                    b.Property<int>("VerificationRequestId")
                        .HasColumnType("int")
                        .HasColumnName("verification_request_id");

                    b.HasKey("Id")
                        .HasName("PK__security__3213E83FEE87294C");

                    b.HasIndex("SecurityId");

                    b.HasIndex("VerificationRequestId");

                    b.ToTable("security_verification_decisions", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.SecurityVerificationRequests", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("RequestedByStaffId")
                        .HasColumnType("int")
                        .HasColumnName("requested_by_staff_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__security__3213E83F08D13778");

                    b.HasIndex("ClaimId");

                    b.HasIndex("RequestedByStaffId");

                    b.ToTable("security_verification_requests", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StaffFoundItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("campus_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedByStaff")
                        .HasColumnType("int")
                        .HasColumnName("created_by_staff");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FoundLocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("found_location");

                    b.Property<DateTime>("FoundTime")
                        .HasColumnType("datetime")
                        .HasColumnName("found_time");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("image_url");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("item_category_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("status");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("storage_location");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__staff_fo__3213E83FE95E9760");

                    b.HasIndex("CampusId");

                    b.HasIndex("CreatedByStaff");

                    b.HasIndex("ItemCategoryId");

                    b.ToTable("staff_found_items", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StaffReturnReceipts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    b.Property<string>("ConfirmedFullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("confirmed_full_name");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("document_number");

                    b.Property<int>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("found_item_id");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("ReturnedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("returned_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SecurityId")
                        .HasColumnType("int")
                        .HasColumnName("security_id");

                    b.Property<int>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("staff_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("PK__staff_re__3213E83F070FD151");

                    b.HasIndex("ClaimId");

                    b.HasIndex("FoundItemId");

                    b.HasIndex("SecurityId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StudentId");

                    b.ToTable("staff_return_receipts", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StudentClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("decided_at");

                    b.Property<int?>("DecidedByStaff")
                        .HasColumnType("int")
                        .HasColumnName("decided_by_staff");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EvidenceUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("evidence_url");

                    b.Property<int>("FoundItemId")
                        .HasColumnType("int")
                        .HasColumnName("found_item_id");

                    b.Property<int?>("LostReportId")
                        .HasColumnType("int")
                        .HasColumnName("lost_report_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__student___3213E83FB6412BAF");

                    b.HasIndex("DecidedByStaff");

                    b.HasIndex("FoundItemId");

                    b.HasIndex("LostReportId");

                    b.HasIndex("StudentId");

                    b.ToTable("student_claims", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StudentLostReports", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int")
                        .HasColumnName("campus_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("item_category_id");

                    b.Property<string>("LostLocation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lost_location");

                    b.Property<DateTime?>("LostTime")
                        .HasColumnType("datetime")
                        .HasColumnName("lost_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__student___3213E83F01D8B12B");

                    b.HasIndex("CampusId");

                    b.HasIndex("ItemCategoryId");

                    b.HasIndex("StudentId");

                    b.ToTable("student_lost_reports", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("student_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__users__3213E83F83CEEE08");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164973DEF48")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.SecurityReceivedItems", b =>
                {
                    b.HasOne("LostAndFound.Domain.Entities.Campus", "Campus")
                        .WithMany("SecurityReceivedItems")
                        .HasForeignKey("CampusId")
                        .IsRequired()
                        .HasConstraintName("FK__security___campu__5EBF139D");

                    b.HasOne("LostAndFound.Domain.Entities.ItemCategories", "ItemCategory")
                        .WithMany("SecurityReceivedItems")
                        .HasForeignKey("ItemCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__security___item___5FB337D6");

                    b.HasOne("LostAndFound.Domain.Entities.Users", "Security")
                        .WithMany("SecurityReceivedItems")
                        .HasForeignKey("SecurityId")
                        .IsRequired()
                        .HasConstraintName("FK__security___secur__60A75C0F");

                    b.Navigation("Campus");

                    b.Navigation("ItemCategory");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.SecurityVerificationDecisions", b =>
                {
                    b.HasOne("LostAndFound.Domain.Entities.Users", "Security")
                        .WithMany("SecurityVerificationDecisions")
                        .HasForeignKey("SecurityId")
                        .IsRequired()
                        .HasConstraintName("FK__security___secur__6D0D32F4");

                    b.HasOne("LostAndFound.Domain.Entities.SecurityVerificationRequests", "VerificationRequest")
                        .WithMany("SecurityVerificationDecisions")
                        .HasForeignKey("VerificationRequestId")
                        .IsRequired()
                        .HasConstraintName("FK__security___verif__6C190EBB");

                    b.Navigation("Security");

                    b.Navigation("VerificationRequest");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.SecurityVerificationRequests", b =>
                {
                    b.HasOne("LostAndFound.Domain.Entities.StudentClaims", "Claim")
                        .WithMany("SecurityVerificationRequests")
                        .HasForeignKey("ClaimId")
                        .IsRequired()
                        .HasConstraintName("FK__security___claim__66603565");

                    b.HasOne("LostAndFound.Domain.Entities.Users", "RequestedByStaff")
                        .WithMany("SecurityVerificationRequests")
                        .HasForeignKey("RequestedByStaffId")
                        .IsRequired()
                        .HasConstraintName("FK__security___reque__6754599E");

                    b.Navigation("Claim");

                    b.Navigation("RequestedByStaff");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StaffFoundItems", b =>
                {
                    b.HasOne("LostAndFound.Domain.Entities.Campus", "Campus")
                        .WithMany("StaffFoundItems")
                        .HasForeignKey("CampusId")
                        .IsRequired()
                        .HasConstraintName("FK__staff_fou__campu__4E88ABD4");

                    b.HasOne("LostAndFound.Domain.Entities.Users", "CreatedByStaffNavigation")
                        .WithMany("StaffFoundItems")
                        .HasForeignKey("CreatedByStaff")
                        .HasConstraintName("FK__staff_fou__creat__5070F446");

                    b.HasOne("LostAndFound.Domain.Entities.ItemCategories", "ItemCategory")
                        .WithMany("StaffFoundItems")
                        .HasForeignKey("ItemCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__staff_fou__item___4F7CD00D");

                    b.Navigation("Campus");

                    b.Navigation("CreatedByStaffNavigation");

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StaffReturnReceipts", b =>
                {
                    b.HasOne("LostAndFound.Domain.Entities.StudentClaims", "Claim")
                        .WithMany("StaffReturnReceipts")
                        .HasForeignKey("ClaimId")
                        .IsRequired()
                        .HasConstraintName("FK__staff_ret__claim__70DDC3D8");

                    b.HasOne("LostAndFound.Domain.Entities.StaffFoundItems", "FoundItem")
                        .WithMany("StaffReturnReceipts")
                        .HasForeignKey("FoundItemId")
                        .IsRequired()
                        .HasConstraintName("FK__staff_ret__found__71D1E811");

                    b.HasOne("LostAndFound.Domain.Entities.Users", "Security")
                        .WithMany("StaffReturnReceiptsSecurity")
                        .HasForeignKey("SecurityId")
                        .HasConstraintName("FK__staff_ret__secur__74AE54BC");

                    b.HasOne("LostAndFound.Domain.Entities.Users", "Staff")
                        .WithMany("StaffReturnReceiptsStaff")
                        .HasForeignKey("StaffId")
                        .IsRequired()
                        .HasConstraintName("FK__staff_ret__staff__72C60C4A");

                    b.HasOne("LostAndFound.Domain.Entities.Users", "Student")
                        .WithMany("StaffReturnReceiptsStudent")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__staff_ret__stude__73BA3083");

                    b.Navigation("Claim");

                    b.Navigation("FoundItem");

                    b.Navigation("Security");

                    b.Navigation("Staff");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StudentClaims", b =>
                {
                    b.HasOne("LostAndFound.Domain.Entities.Users", "DecidedByStaffNavigation")
                        .WithMany("StudentClaimsDecidedByStaffNavigation")
                        .HasForeignKey("DecidedByStaff")
                        .HasConstraintName("FK__student_c__decid__59063A47");

                    b.HasOne("LostAndFound.Domain.Entities.StaffFoundItems", "FoundItem")
                        .WithMany("StudentClaims")
                        .HasForeignKey("FoundItemId")
                        .IsRequired()
                        .HasConstraintName("FK__student_c__found__571DF1D5");

                    b.HasOne("LostAndFound.Domain.Entities.StudentLostReports", "LostReport")
                        .WithMany("StudentClaims")
                        .HasForeignKey("LostReportId")
                        .HasConstraintName("FK__student_c__lost___5812160E");

                    b.HasOne("LostAndFound.Domain.Entities.Users", "Student")
                        .WithMany("StudentClaimsStudent")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__student_c__stude__5629CD9C");

                    b.Navigation("DecidedByStaffNavigation");

                    b.Navigation("FoundItem");

                    b.Navigation("LostReport");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StudentLostReports", b =>
                {
                    b.HasOne("LostAndFound.Domain.Entities.Campus", "Campus")
                        .WithMany("StudentLostReports")
                        .HasForeignKey("CampusId")
                        .IsRequired()
                        .HasConstraintName("FK__student_l__campu__46E78A0C");

                    b.HasOne("LostAndFound.Domain.Entities.ItemCategories", "ItemCategory")
                        .WithMany("StudentLostReports")
                        .HasForeignKey("ItemCategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__student_l__item___47DBAE45");

                    b.HasOne("LostAndFound.Domain.Entities.Users", "Student")
                        .WithMany("StudentLostReports")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__student_l__stude__45F365D3");

                    b.Navigation("Campus");

                    b.Navigation("ItemCategory");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.Campus", b =>
                {
                    b.Navigation("SecurityReceivedItems");

                    b.Navigation("StaffFoundItems");

                    b.Navigation("StudentLostReports");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.ItemCategories", b =>
                {
                    b.Navigation("SecurityReceivedItems");

                    b.Navigation("StaffFoundItems");

                    b.Navigation("StudentLostReports");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.SecurityVerificationRequests", b =>
                {
                    b.Navigation("SecurityVerificationDecisions");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StaffFoundItems", b =>
                {
                    b.Navigation("StaffReturnReceipts");

                    b.Navigation("StudentClaims");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StudentClaims", b =>
                {
                    b.Navigation("SecurityVerificationRequests");

                    b.Navigation("StaffReturnReceipts");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.StudentLostReports", b =>
                {
                    b.Navigation("StudentClaims");
                });

            modelBuilder.Entity("LostAndFound.Domain.Entities.Users", b =>
                {
                    b.Navigation("SecurityReceivedItems");

                    b.Navigation("SecurityVerificationDecisions");

                    b.Navigation("SecurityVerificationRequests");

                    b.Navigation("StaffFoundItems");

                    b.Navigation("StaffReturnReceiptsSecurity");

                    b.Navigation("StaffReturnReceiptsStaff");

                    b.Navigation("StaffReturnReceiptsStudent");

                    b.Navigation("StudentClaimsDecidedByStaffNavigation");

                    b.Navigation("StudentClaimsStudent");

                    b.Navigation("StudentLostReports");
                });
#pragma warning restore 612, 618
        }
    }
}
