using LostAndFound.Application.Interfaces;
using LostAndFound.Domain.Entities;
using Microsoft.AspNetCore.Mvc;

namespace LostAndFound.Api.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class CampusesController : ControllerBase
    {
        private readonly ICampusService _service;

        public CampusesController(ICampusService service)
        {
            _service = service;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var data = await _service.GetAllAsync();
            return Ok(data);
        }

        [HttpGet("{id:int}")]
        public async Task<IActionResult> GetById(int id)
        {
            var campus = await _service.GetByIdAsync(id);
            if (campus == null) return NotFound();
            return Ok(campus);
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] Campus campus)
        {
            // Ensure identity column is generated by DB
            campus.Id = 0;
            var created = await _service.CreateAsync(campus);
            return CreatedAtAction(nameof(GetById), new { id = created.Id }, created);
        }

        [HttpPut("{id:int}")]
        public async Task<IActionResult> Update(int id, [FromBody] Campus campus)
        {
            var updated = await _service.UpdateAsync(id, campus);
            if (updated == null) return NotFound();
            return Ok(updated);
        }

        [HttpDelete("{id:int}")]
        public async Task<IActionResult> Delete(int id)
        {
            var deleted = await _service.DeleteAsync(id);
            if (!deleted) return NotFound();
            return NoContent();
        }
    }
}